openapi: 3.0.0
info:
  title: Chat API
  description: API for chat functionality
  version: 1.0.0
servers:
  - url: http://localhost:8000
  - url: https://kact-staging.azurewebsites.net/

paths:
  /health:
    get:
      summary: Health check
      operationId: healthCheck
      responses:
        '200':
          description: Health check success
          content:
            application/json:
              schema:
                properties:
                  message: 
                    type: string
                    example: "Hello World!"
